import { expect, test } from "@playwright/test";
import { createServer as createHttpServer, type Server } from "node:http";
import { createServer as createViteServer, type ViteDevServer } from "vite";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

let api: Server; let vite: ViteDevServer; let origin: string; let resultRoot: string;
test.beforeAll(async () => {
  api = createHttpServer((req, res) => { if (req.url === "/demo") { res.writeHead(200, { "content-type": "text/html" }); return res.end(`<button id="retry">Retry</button><pre data-testid="result"></pre><script>retry.onclick=async()=>{const r=await fetch('/exports/running-export/retry',{method:'POST',headers:{Authorization:'Bearer demo-secret','Content-Type':'application/json'},body:JSON.stringify({token:'body-secret',force:false})});document.querySelector('pre').textContent=await r.text()}</script>`); } const id = req.url?.match(/\/exports\/([^/]+)\/retry/)?.[1]; const status = id === "running-export" ? 409 : id === "missing-export" ? 404 : id === "failure" ? 500 : 200; res.writeHead(status, { "content-type": "application/json", "set-cookie": "session=secret" }); res.end(JSON.stringify(status === 200 ? { status: "queued" } : { code: status === 409 ? "EXPORT_ALREADY_RUNNING" : status === 404 ? "EXPORT_NOT_FOUND" : "QUEUE_UNAVAILABLE" })); }); await new Promise<void>((resolve) => api.listen(0, "127.0.0.1", resolve)); const apiAddress = api.address(); const apiUrl = `http://127.0.0.1:${typeof apiAddress === "object" && apiAddress ? apiAddress.port : 0}`; process.env.BAEKSTAGE_DEMO_API_URL = apiUrl; process.env.VITE_BAEKSTAGE_DEMO_API_URL = apiUrl;
  process.env.BAEKSTAGE_DEMO_PAGE_URL = `${apiUrl}/demo`; resultRoot = await mkdtemp(path.join(tmpdir(), "baekstage-e2e-")); process.env.BAEKSTAGE_RESULT_ROOT = resultRoot; vite = await createViteServer({ configFile: "vite.config.ts", logLevel: "silent", server: { host: "127.0.0.1", port: 0 } }); await vite.listen(); const address = vite.httpServer?.address(); origin = `http://127.0.0.1:${typeof address === "object" && address ? address.port : 0}`;
});
test.afterAll(async () => { await vite.close(); api.close(); await rm(resultRoot, { recursive: true }); });

test("expected 409 branch passes and updates response coverage", async ({ page }) => {
  await page.goto(origin); await page.getByRole("button", { name: "Catalog" }).click(); await page.getByText("/exports/{id}/retry").click(); await page.getByLabel("Test case").selectOption("already-running"); await expect(page.getByLabel("Path id")).toHaveValue("running-export"); await page.getByRole("button", { name: "Run request" }).click();
  await expect(page.getByText(/409 Conflict · Test passed/)).toBeVisible(); await expect(page.getByText(/Branch: .*response:409/)).toBeVisible(); await expect(page.getByText(/Tested · passed/)).toBeVisible();
  await page.getByLabel("Test case").selectOption("unexpected-server-error"); await page.getByRole("button", { name: "Run request" }).click(); await expect(page.getByText(/500 Internal Server Error · Test failed/)).toBeVisible(); await expect(page.getByText("Failure: unexpected-status")).toBeVisible(); await expect(page.getByText(/Tested · failed/)).toBeVisible(); await expect(page.getByLabel("Replay history").locator("option")).toHaveCount(2);
});

test("runs a neutral scenario against the local Playwright demo", async () => { const run = await fetch(`${origin}/api/scenarios/checkout-success/run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source: "e2e/fixtures/demo-flow.spec.ts", grep: "C-01" }) }); expect(run.ok).toBeTruthy(); const result = await run.json(); expect(result).toMatchObject({ scenarioId: "checkout-success", adapter: "playwright", status: "passed" }); expect(result.screenshots).toHaveLength(3); expect(result.screenshots.map((item: { nodeId: string }) => item.nodeId)).toEqual(["before", "action", "after"]); });

test("runs the retry UI demo, captures screens, and links the observed API node", async () => { const run = await fetch(`${origin}/api/scenarios/retry-failed-export/run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source: "e2e/fixtures/demo-flow.spec.ts", grep: "R-01" }) }); expect(run.ok).toBeTruthy(); const result = await run.json(); expect(result).toMatchObject({ scenarioId: "retry-failed-export", adapter: "playwright", status: "passed" }); expect(result.screenshots.map((item: { nodeId: string }) => item.nodeId)).toEqual(["failed-screen", "already-running"]); expect(result.nodeResults).toContainEqual(expect.objectContaining({ nodeId: "retry-request", caseId: "already-running", status: "passed", api: expect.objectContaining({ response: expect.objectContaining({ status: 409, matchType: "exact" }) }) })); });

test("observes a real UI request, maps 409, replays 200, and shows a diff", async ({ page }) => {
  const run = await fetch(`${origin}/api/scenarios/retry-failed-export/run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source: "e2e/fixtures/retry-observed.spec.ts", grep: "observes retry" }) });
  expect(run.ok).toBeTruthy(); const manifest = await run.json(); expect(manifest.nodeResults[0]).toMatchObject({ origin: "playwright", nodeId: "retry-request", caseId: "already-running", status: "passed", api: { operationMatch: "matched", caseMatch: "matched", step: { id: "click-retry" }, response: { status: 409, matchType: "exact" } } }); expect(JSON.stringify(manifest)).not.toContain("demo-secret"); expect(JSON.stringify(manifest)).not.toContain("body-secret"); expect(JSON.stringify(manifest)).not.toContain("session=secret");
  await page.goto(origin); await page.getByRole("button", { name: "Catalog" }).click(); await page.getByText("/exports/{id}/retry").click(); await expect(page.getByText("Observed in Playwright run")).toBeVisible(); await expect(page.getByText(/409 Conflict/).first()).toBeVisible(); await expect(page.getByText("click-retry", { exact: true })).toBeVisible(); await expect(page.getByText("Request body: not stored")).toBeVisible(); await expect(page.getByLabel("Path id")).toHaveValue("running-export"); await expect(page.getByLabel("JSON request body")).toHaveValue("");
  await page.getByLabel("Test case").selectOption("accepted"); await page.getByRole("button", { name: "Run request" }).click(); await expect(page.getByText(/200 OK · Test passed/)).toBeVisible(); await expect(page.getByRole("heading", { name: "Observed → Replay" })).toBeVisible(); const diff = page.locator(".response-diff"); await expect(diff).toContainText("409"); await expect(diff).toContainText("200"); await expect(diff).toContainText("body.status");
});
