import { describe, expect, it } from "vitest";
import { createBaekstageTest, observeApiScenario, readNetworkAttachmentName, readStepAttachmentName } from "./observe-api-scenario";

class FakePage { listeners = new Map<string, Set<Function>>(); on(event: string, listener: Function) { const values = this.listeners.get(event) ?? new Set(); values.add(listener); this.listeners.set(event, values); } off(event: string, listener: Function) { this.listeners.get(event)?.delete(listener); } emit(event: string, value: unknown) { this.listeners.get(event)?.forEach((listener) => listener(value)); } count() { return [...this.listeners.values()].reduce((sum, values) => sum + values.size, 0); } }
const request = (url = "https://api.test/jobs/abc?access_token=secret") => ({ method: () => "POST", url: () => url, headers: () => ({ Authorization: "Bearer secret" }), postDataJSON: () => ({ password: "secret", force: false }), failure: () => ({ errorText: "net::ERR_ABORTED" }) });
const response = (value: ReturnType<typeof request>, status = 409) => ({ request: () => value, status: () => status, statusText: () => "Conflict", headers: () => ({ "content-type": "application/json", "set-cookie": "secret=yes" }), body: async () => new TextEncoder().encode(JSON.stringify({ code: "CONFLICT", token: "secret" })) });

describe("Playwright API observation", () => {
  it("captures concurrent redacted evidence, step results, filters, and cleans listeners", async () => { const page = new FakePage(); const attachments = new Map<string, Buffer>(); const observer = observeApiScenario(page as any, { attach: async (label, value) => { attachments.set(label, value.body); } }, { scenarioId: "retry", includeRequestBody: true, exclude: ["**/health"] }); const first = request(); const second = request("https://api.test/health"); await observer.step({ id: "click", toNodeId: "api", edgeId: "edge" }, async () => { page.emit("request", first); page.emit("request", second); }); page.emit("response", response(first)); page.emit("requestfailed", second); await observer.flush(); await observer.flush(); const networkEntry = [...attachments].find(([name]) => readNetworkAttachmentName(name)); const stepEntry = [...attachments].find(([name]) => readStepAttachmentName(name)); expect(readNetworkAttachmentName(networkEntry![0])).toEqual({ scenarioId: "retry" }); expect(readStepAttachmentName(stepEntry![0])).toEqual({ scenarioId: "retry" }); const records = JSON.parse(networkEntry![1].toString("utf8")); const steps = JSON.parse(stepEntry![1].toString("utf8")); expect(records[0]).toMatchObject({ step: { id: "click", edgeId: "edge" }, request: { body: { password: "[REDACTED]" } }, response: { status: 409, body: { token: "[REDACTED]" } } }); expect(records[1]).toMatchObject({ matchStatus: "ignored", error: "net::ERR_ABORTED" }); expect(steps).toMatchObject([{ marker: { id: "click", toNodeId: "api", edgeId: "edge" }, status: "passed" }]); expect(JSON.stringify(records)).not.toMatch(/Bearer secret|session=secret/); expect(page.count()).toBe(0); });
  it("records a failed terminal step before rethrowing", async () => { const page = new FakePage(); const attachments = new Map<string, Buffer>(); const observer = observeApiScenario(page as any, { attach: async (label, value) => { attachments.set(label, value.body); } }, { scenarioId: "branch" }); await expect(observer.step("terminal-five", async () => { throw new Error("secret failure"); })).rejects.toThrow("secret failure"); await observer.flush(); const entry = [...attachments].find(([name]) => readStepAttachmentName(name)); expect(JSON.parse(entry![1].toString("utf8"))).toMatchObject([{ marker: { id: "terminal-five" }, status: "failed", error: "secret failure" }]); });
  it("waits for a response event that arrives while flush is draining", async () => { const page = new FakePage(); let records: any[] = []; const observer = observeApiScenario(page as any, { attach: async (name, value) => { if (readNetworkAttachmentName(name)) records = JSON.parse(value.body.toString()); } }, { scenarioId: "retry", flushTimeoutMs: 200 }); const value = request(); page.emit("request", value); const flushing = observer.flush(); setTimeout(() => page.emit("response", response(value)), 20); await flushing; expect(records[0].response.status).toBe(409); });
  it("prevents duplicate observers on one page", async () => { const page = new FakePage(); const info = { attach: async () => {} }; const observer = observeApiScenario(page as any, info, { scenarioId: "one", flushTimeoutMs: 1 }); expect(() => observeApiScenario(page as any, info, { scenarioId: "two" })).toThrow(/already active/); await observer.flush(); });
  it("fixture flushes evidence after a failing test body", async () => { const page = new FakePage(); let attached = false; let fixtureFactory: Function | undefined; const base = { extend: (fixtures: any) => { fixtureFactory = fixtures.baekstage; return fixtures; } }; createBaekstageTest(base, { scenarioIdFromTest: ({ title }) => title }); await expect(fixtureFactory!({ page }, async () => { const value = request(); page.emit("request", value); page.emit("requestfailed", value); throw new Error("test failed"); }, { title: "scenario", attach: async () => { attached = true; } })).rejects.toThrow("test failed"); expect(attached).toBe(true); expect(page.count()).toBe(0); });
});
