// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import "@testing-library/jest-dom/vitest";
import { useState } from "react";
import { ApiCatalogView } from "./ApiCatalog";
import { ApiWorkbench } from "./ApiWorkbench";
import { parseOpenApiDocument } from "../../openapi/catalog";
import type { ScenarioRunResult, ScenarioSuite } from "../../core/types";
import { applyRunResult } from "../../core/execution";

const catalog = parseOpenApiDocument({ id: "api", title: "Example API", baseUrl: "http://localhost:3000" }, { openapi: "3.0.0", paths: { "/items/{id}": { get: { tags: ["Items"], operationId: "getItem", parameters: [{ name: "id", in: "path", required: true }], responses: { "200": { description: "OK", content: { "application/json": { example: { id: "one" } } } }, "409": { description: "Conflict", content: { "application/json": { schema: { type: "object", required: ["code"] }, example: { code: "CONFLICT" } } } } } } } } });
const suite: ScenarioSuite = { name: "Suite", scenarios: [{ id: "item", title: "Read item", nodes: [{ id: "request", title: "GET item", kind: "api", ref: catalog.operations[0].id, cases: [{ id: "ok", title: "Success", expectedResponse: "200", request: { path: { id: "one" } }, assertions: [{ type: "status", equals: 200 }] }, { id: "conflict", title: "Expected conflict", expectedResponse: "409", request: { path: { id: "conflict" } }, assertions: [{ type: "status", equals: 409 }] }] }], edges: [] }] };
function Harness({ onResult }: { onResult: (result: ScenarioRunResult) => void }) { const [scenario, setScenario] = useState(suite.scenarios[0]); return <ApiWorkbench operation={catalog.operations[0]} scenario={scenario} node={scenario.nodes[0]} onResult={(result) => { setScenario((current) => applyRunResult(current, result)); onResult(result); }}/>; }

afterEach(() => { cleanup(); vi.restoreAllMocks(); });
describe("API viewer interactions", () => {
  it("searches and selects a catalog endpoint", async () => { const onSelect = vi.fn(); render(<ApiCatalogView catalog={catalog} suite={suite} onSelect={onSelect}/>); await userEvent.type(screen.getByLabelText("Search APIs"), "getItem"); await userEvent.click(screen.getByText("/items/{id}")); expect(onSelect).toHaveBeenCalledWith(catalog.operations[0]); });
  it("selects a response case, runs it, renders expected error as passed, and returns the node result", async () => {
    let resolveRun!: (response: Response) => void; let requestBody: any; const result: ScenarioRunResult = { runId: "run-409", origin: "api-replay", scenarioId: "item", adapter: "api", status: "passed", screenshots: [], output: "", startedAt: "2026-01-01T00:00:00Z", finishedAt: "2026-01-01T00:00:01Z", nodeResults: [{ runId: "run-409", origin: "api-replay", nodeId: "request", caseId: "conflict", status: "passed", assertions: [{ assertion: { type: "status", equals: 409 }, status: "passed", message: "status equals 409", expected: 409, actual: 409 }], api: { request: { timestamp: "2026-01-01T00:00:00Z", method: "GET", url: "http://localhost:3000/items/conflict", headers: {}, bodyStored: false }, response: { status: 409, statusText: "Conflict", durationMs: 12, headers: { "content-type": "application/json" }, body: { code: "CONFLICT" }, documented: true, branchId: `${catalog.operations[0].id}:response:409`, matchType: "exact" } } }] };
    vi.stubGlobal("fetch", vi.fn(async (_url: string, init?: RequestInit) => { if (!init) return new Response("[]", { status: 200 }); requestBody = JSON.parse(String(init.body)); return new Promise<Response>((resolve) => { resolveRun = resolve; }); })); const onResult = vi.fn(); render(<Harness onResult={onResult}/>);
    await userEvent.selectOptions(screen.getByLabelText("Test case"), "conflict"); expect(screen.getByLabelText("Path id")).toHaveValue("conflict"); await userEvent.click(screen.getByRole("button", { name: "Run request" })); expect(screen.getByRole("button", { name: "Running…" })).toBeDisabled(); resolveRun(new Response(JSON.stringify(result), { status: 200, headers: { "content-type": "application/json" } }));
    await screen.findByText(/409 Conflict · Test passed/); expect(screen.getByText(/Branch:/)).toHaveTextContent("response:409"); expect(requestBody).toMatchObject({ caseId: "conflict", expectedResponse: "409", path: { id: "conflict" } }); expect(onResult).toHaveBeenCalledWith(result); await waitFor(() => expect(screen.getByText(/Tested · passed/)).toBeInTheDocument());
  });
  it("selects observed and replay history and renders stored-only field differences", async () => { const observedNode = { runId: "observed", origin: "playwright" as const, nodeId: "request", caseId: "conflict", status: "failed" as const, failureKind: "assertion-failed" as const, assertions: [{ assertion: { type: "json-path" as const, path: "$.code", equals: "EXPECTED" }, status: "failed" as const, message: "body.code equals EXPECTED", expected: "EXPECTED", actual: "CONFLICT" }], api: { operationMatch: "matched" as const, caseMatch: "matched" as const, step: { id: "click-retry" }, request: { timestamp: "2026-01-01T00:00:00Z", method: "GET", url: "http://localhost:3000/items/conflict", headers: { Authorization: "[REDACTED]" }, bodyStored: false, bodyStorageReason: "disabled" as const }, response: { status: 409, statusText: "Conflict", durationMs: 20, headers: {}, body: { code: "CONFLICT" }, documented: true, branchId: `${catalog.operations[0].id}:response:409`, matchType: "exact" as const } } }; const replayNode = { ...observedNode, runId: "replay", origin: "api-replay" as const, status: "passed" as const, failureKind: undefined, api: { ...observedNode.api, request: { ...observedNode.api.request, bodyStored: false }, response: { ...observedNode.api.response, status: 200, statusText: "OK", body: { id: "one" }, branchId: `${catalog.operations[0].id}:response:200` } } }; const history: ScenarioRunResult[] = [{ runId: "observed", origin: "playwright", scenarioId: "item", status: "failed", screenshots: [], output: "", startedAt: "2026-01-01T00:00:00Z", finishedAt: "2026-01-01T00:00:01Z", nodeResults: [observedNode] }, { runId: "replay", origin: "api-replay", scenarioId: "item", status: "passed", screenshots: [], output: "", startedAt: "2026-01-01T00:01:00Z", finishedAt: "2026-01-01T00:01:01Z", nodeResults: [replayNode] }]; vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify(history), { status: 200, headers: { "content-type": "application/json" } }))); render(<Harness onResult={() => {}}/>); await screen.findByText("Observed in Playwright run"); expect(screen.getByText(/UI step:/)).toHaveTextContent("click-retry"); expect(screen.getByText("Request body: not stored")).toBeVisible(); expect(screen.getByRole("heading", { name: "Observed → Replay" })).toBeVisible(); expect(screen.getByText("body.code").closest("tr")).toHaveTextContent("CONFLICT"); expect(document.body.textContent).not.toContain("Bearer secret"); });
});
