import { useEffect, useMemo, useState } from "react";
import type { ApiAssertion, OpenApiOperation, ScenarioApiCase, ScenarioGraph, ScenarioNode, ScenarioNodeResult } from "../../core/types";
import { isSensitiveHeader, redactValue } from "../../core/security";
import { normalizeApiCases } from "../../core/api-cases";
import { responseBranchCoverage } from "../../core/api-response";
import { useApiRun, type ApiRunResponse } from "../../hooks/api/use-api-run";

const objectText = (value: unknown) => value === undefined ? "" : JSON.stringify(value, null, 2);
function initialObject(operation: OpenApiOperation, location: "path" | "query") { return Object.fromEntries(operation.parameters.filter((item) => item.in === location).map((item) => [item.name, item.example ?? ""])); }
function structuredAssertions(testCase?: ScenarioApiCase): ApiAssertion[] { return (testCase?.assertions ?? []).filter((item): item is ApiAssertion => typeof item !== "string"); }
function responseOf(result?: ApiRunResponse | ScenarioNodeResult | null) { return "nodeResults" in (result ?? {}) ? (result as ApiRunResponse).nodeResults?.[0]?.api?.response : (result as ScenarioNodeResult | undefined)?.api?.response; }
function flatten(value: unknown, prefix = "", output: Record<string, unknown> = {}, count = { value: 0 }) { if (count.value >= 100) return output; if (Array.isArray(value)) { value.slice(0, 20).forEach((item, index) => flatten(item, `${prefix}[${index}]`, output, count)); return output; } if (value && typeof value === "object") { Object.entries(value as Record<string, unknown>).forEach(([key, item]) => flatten(item, prefix ? `${prefix}.${key}` : key, output, count)); return output; } output[prefix || "value"] = value; count.value++; return output; }
function comparisonRows(observed?: ScenarioNodeResult, replay?: ScenarioNodeResult) { const left = observed?.api; const right = replay?.api; if (!left || !right) return []; const parts = (value: string) => { try { const url = new URL(value); return { path: url.pathname, query: [...url.searchParams].sort().map(([key, item]) => `${key}=${item}`).join("&") }; } catch { return { path: value, query: "" }; } }; const leftUrl = parts(left.request.url), rightUrl = parts(right.request.url); const fixed: Array<[string, unknown, unknown]> = [["method", left.request.method, right.request.method], ["path", leftUrl.path, rightUrl.path], ["query", leftUrl.query, rightUrl.query], ["status", left.response?.status, right.response?.status], ["branch", left.response?.branchId, right.response?.branchId], ["content type", left.response?.contentType, right.response?.contentType], ["schema valid", left.response?.schemaValid, right.response?.schemaValid], ["duration", left.response?.durationMs, right.response?.durationMs], ["failure", observed.failureKind, replay.failureKind]]; const headerKeys = [...new Set([...Object.keys(left.request.headers), ...Object.keys(right.request.headers)])].filter((key) => !isSensitiveHeader(key)); const headerRows = headerKeys.map((key): [string, unknown, unknown] => [`header.${key}`, left.request.headers[key], right.request.headers[key]]); const leftBody = left.response?.body === undefined ? {} : flatten(left.response.body); const rightBody = right.response?.body === undefined ? {} : flatten(right.response.body); const keys = [...new Set([...Object.keys(leftBody), ...Object.keys(rightBody)])].slice(0, 100); return [...fixed, ...headerRows, ...keys.map((key): [string, unknown, unknown] => [`body.${key}`, leftBody[key], rightBody[key]])]; }
function observedInput(operation: OpenApiOperation, result?: ScenarioNodeResult) { const request = result?.api?.request; if (!request) return undefined; try { const url = new URL(request.url); const names = [...operation.path.matchAll(/\{([^}]+)\}/g)].map((item) => item[1]); const expression = new RegExp(`^${operation.path.split(/\{[^}]+\}/).map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("([^/]+)")}$`); const values = url.pathname.match(expression)?.slice(1) ?? []; return { path: Object.fromEntries(names.map((name, index) => [name, decodeURIComponent(values[index] ?? "")])), query: Object.fromEntries(url.searchParams), headers: Object.fromEntries(Object.entries(request.headers).filter(([name, value]) => !isSensitiveHeader(name) && value !== "[REDACTED]")), body: request.bodyStored ? request.body : undefined }; } catch { return undefined; } }

export function ApiWorkbench({ operation, scenario, node, endpoint, onResult, onClose }: { operation: OpenApiOperation; scenario?: ScenarioGraph; node?: ScenarioNode; endpoint?: string; onResult: (result: ApiRunResponse) => void; onClose?: () => void }) {
  const cases = useMemo(() => node ? normalizeApiCases(node) : [], [node]); const [caseId, setCaseId] = useState("");
  const [pathValues, setPathValues] = useState<Record<string, unknown>>({}); const [query, setQuery] = useState<Record<string, unknown>>({}); const [headers, setHeaders] = useState("{}"); const [body, setBody] = useState("");
  const [environment, setEnvironment] = useState(""); const [inputError, setInputError] = useState<string | null>(null); const [observedRunId, setObservedRunId] = useState(""); const [replayRunId, setReplayRunId] = useState("");
  const runner = useApiRun(endpoint, onResult); const selectedCase = cases.find((item) => item.id === caseId) ?? cases[0]; const observedRuns = runner.history.filter((item) => item.origin === "playwright"); const replayRuns = runner.history.filter((item) => item.origin === "api-replay"); const observedRun = observedRuns.find((item) => item.runId === observedRunId) ?? observedRuns.at(-1); const observed = observedRun?.nodeResults?.find((item) => item.nodeId === node?.id) ?? node?.resultHistory?.filter((item) => item.origin === "playwright").at(-1); const observedValues = observedInput(operation, observed);
  const fillCase = (testCase?: ScenarioApiCase, observedOverride?: ReturnType<typeof observedInput>) => { setCaseId(testCase?.id ?? ""); setPathValues({ ...initialObject(operation, "path"), ...testCase?.request?.path, ...observedOverride?.path }); setQuery({ ...initialObject(operation, "query"), ...testCase?.request?.query, ...observedOverride?.query }); setHeaders(objectText(observedOverride?.headers ?? testCase?.request?.headers ?? { "Content-Type": "application/json" })); setBody(objectText(observedOverride ? observedOverride.body : testCase?.request?.body ?? operation.requestBody?.media[0]?.example)); };
  useEffect(() => { fillCase(cases.find((item) => item.id === observed?.caseId) ?? cases[0], observedValues); setEnvironment(Object.keys(operation.environments ?? {})[0] ?? ""); runner.clear(); if (scenario && node) runner.loadHistory(scenario.id, node.id); }, [operation.id, node?.id, observed?.runId]);
  const replayResults = runner.history.flatMap((item) => item.nodeResults ?? []); const coverage = useMemo(() => responseBranchCoverage(operation, scenario, node?.id, replayResults), [operation, scenario, node, runner.history]);
  const selectedHistory = replayRuns.find((item) => item.runId === replayRunId); const latest = selectedHistory ?? runner.result ?? replayRuns.at(-1); const replayNode = latest?.nodeResults?.find((item) => item.nodeId === node?.id); const response = responseOf(latest); const observedResponse = responseOf(observed); const diffRows = comparisonRows(observed, replayNode);
  const curl = useMemo(() => { const requestPath = operation.path.replace(/\{([^}]+)\}/g, (_, key) => encodeURIComponent(String(pathValues[key] ?? `{${key}}`))); const base = environment ? operation.environments?.[environment] : operation.baseUrl; const url = new URL(requestPath, `${base ?? "http://base-url.invalid"}/`); for (const [key, value] of Object.entries(query)) if (value !== "") url.searchParams.set(key, String(value)); let value = `curl -X ${operation.method} '${url.toString()}'`; try { for (const [key, item] of Object.entries(JSON.parse(headers))) value += ` -H '${key}: ${isSensitiveHeader(key) ? "[REDACTED]" : item}'`; } catch {} if (body) { try { value += ` --data '${JSON.stringify(redactValue(JSON.parse(body))).replaceAll("'", "'\\''")}'`; } catch {} } return value; }, [body, environment, headers, operation, pathValues, query]);
  const execute = () => { if (!scenario || !node || !selectedCase) return; if (selectedCase.setup && selectedCase.setup.type !== "request-only") { setInputError(`Case setup '${selectedCase.setup.type}' requires external preparation.`); return; } setInputError(null); try { runner.run({ sourceId: operation.sourceId, operationId: operation.id, scenarioId: scenario.id, nodeId: node.id, caseId: selectedCase.id, expectedResponse: selectedCase.expectedResponse, environment: environment || undefined, path: pathValues, query, headers: JSON.parse(headers || "{}"), body: body ? JSON.parse(body) : undefined, assertions: structuredAssertions(selectedCase) }); } catch (error) { setInputError(`Invalid JSON input: ${error instanceof Error ? error.message : String(error)}`); } };
  return <aside className="api-workbench" aria-label="API request workbench">
    <header><div><small>{operation.sourceTitle}</small><h2><span className={`method ${operation.method.toLowerCase()}`}>{operation.method}</span> {operation.path}</h2></div>{onClose && <button onClick={onClose} aria-label="Close workbench">×</button>}</header>
    <p>{operation.summary ?? operation.description}</p>
    <section className="response-branches"><h3>Response branches</h3>{coverage.map((item) => <button key={item.branch.id} onClick={() => { const found = cases.find((testCase) => testCase.expectedResponse?.toLowerCase() === item.branch.statusPattern.toLowerCase()); if (found) fillCase(found); }}><strong>{item.status === "passed" ? "✓" : item.status === "failed" ? "✕" : "○"} {item.branch.statusPattern} {item.branch.title}</strong><small>{[item.connected ? "Connected" : "Unmodeled", item.hasCase ? "Case defined" : "No case", item.tested ? `Tested · ${item.status}` : "Untested"].join(" · ")}</small>{!item.hasCase && <em>명세에 정의되어 있지만 재현 조건이 없습니다.</em>}</button>)}</section>
    {!!cases.length && <label>Test case<select aria-label="Test case" value={selectedCase?.id ?? ""} onChange={(event) => fillCase(cases.find((item) => item.id === event.target.value))}>{cases.map((item) => <option value={item.id} key={item.id}>{item.title} · expected {item.expectedResponse ?? "2xx"}</option>)}</select></label>}
    {Object.keys(operation.environments ?? {}).length > 0 && <label>Environment<select value={environment} onChange={(event) => setEnvironment(event.target.value)}>{Object.keys(operation.environments ?? {}).map((name) => <option key={name}>{name}</option>)}</select></label>}<label>Base URL<input value={environment ? operation.environments?.[environment] : operation.baseUrl ?? "Not configured"} readOnly/></label>
    {!!operation.parameters.filter((item) => item.in === "path").length && <fieldset><legend>Path parameters</legend>{operation.parameters.filter((item) => item.in === "path").map((item) => <label key={item.name}>{item.name}{item.required ? " *" : ""}<input aria-label={`Path ${item.name}`} value={String(pathValues[item.name] ?? "")} onChange={(event) => setPathValues({ ...pathValues, [item.name]: event.target.value })}/></label>)}</fieldset>}
    {!!operation.parameters.filter((item) => item.in === "query").length && <fieldset><legend>Query parameters</legend>{operation.parameters.filter((item) => item.in === "query").map((item) => <label key={item.name}>{item.name}<input aria-label={`Query ${item.name}`} value={String(query[item.name] ?? "")} onChange={(event) => setQuery({ ...query, [item.name]: event.target.value })}/></label>)}</fieldset>}
    <label>Headers <small>Sensitive values are never persisted.</small><textarea aria-label="Headers" value={headers} onChange={(event) => setHeaders(event.target.value)} spellCheck={false} autoComplete="off"/></label><label>JSON request body<textarea aria-label="JSON request body" value={body} onChange={(event) => setBody(event.target.value)} spellCheck={false}/></label>
    <div className="workbench-actions"><button onClick={execute} disabled={!scenario || !node || runner.running}>{runner.running ? "Running…" : "Run request"}</button><button onClick={() => navigator.clipboard?.writeText(curl)}>Copy redacted curl</button></div>
    {!scenario && <p className="notice">이 endpoint를 실행하려면 연결된 Scenario API node가 필요합니다.</p>}{(inputError || runner.error) && <p className="api-error">{inputError ?? runner.error}</p>}
    {observed && <section className="observed-response"><h3>Observed in Playwright run</h3>{observedRuns.length > 0 && <label>Observed history<select aria-label="Observed history" value={observedRun?.runId ?? ""} onChange={(event) => { setObservedRunId(event.target.value); const selected = observedRuns.find((item) => item.runId === event.target.value)?.nodeResults?.find((item) => item.nodeId === node?.id); fillCase(cases.find((item) => item.id === selected?.caseId) ?? cases[0], observedInput(operation, selected)); }} >{observedRuns.map((item) => <option value={item.runId} key={item.runId}>{new Date(item.finishedAt).toLocaleString()} · {item.status}</option>)}</select></label>}<strong>{observedResponse ? `${observedResponse.status} ${observedResponse.statusText}` : observed.error}</strong><small>{observed.api?.operationMatch ?? "unknown"} · {observedResponse?.branchId ?? "No response branch"} · case {observed.api?.caseMatch ?? "observed-only"}</small>{observed.api?.step && <p>UI step: <strong>{observed.api.step.id}</strong>{observed.api.step.edgeId ? ` · edge ${observed.api.step.edgeId}` : ""}</p>}<p>Request body: {observed.api?.request.bodyStored ? "stored with redaction" : "not stored"}</p>{observed.assertions?.map((item, index) => <div className={`assertion ${item.status}`} key={index}><strong>{item.status}</strong> {item.message}{item.status === "failed" && <small>expected: {objectText(item.expected)} actual: {objectText(item.actual)}</small>}</div>)}<details><summary>Observed request</summary><pre>{objectText({ method: observed.api?.request.method, url: observed.api?.request.url, headers: observed.api?.request.headers, body: observed.api?.request.bodyStored ? observed.api.request.body : "not stored", step: observed.api?.step })}</pre></details></section>}
    {!!replayRuns.length && <label className="replay-history"><span>Replay history</span><small>이전 실행 결과를 선택해 response와 diff를 확인합니다.</small><select aria-label="Replay history" value={latest?.runId ?? ""} onChange={(event) => setReplayRunId(event.target.value)}>{replayRuns.map((item) => <option value={item.runId} key={item.runId}>{new Date(item.finishedAt).toLocaleString()} · {item.status} · {item.nodeResults?.[0]?.caseId}</option>)}</select></label>}
    {response && <section className="api-response" aria-live="polite"><h3><span className={latest?.status}>{response.status} {response.statusText} · Test {latest?.status}</span><small>{response.durationMs} ms</small></h3><p>{response.documented ? `Branch: ${response.branchId} (${response.matchType})` : "Observed · Undocumented response"}</p><details><summary>Response headers</summary><pre>{objectText(response.headers)}</pre></details><pre>{objectText(response.body)}</pre>{latest?.nodeResults?.[0]?.assertions?.map((item, index) => <div className={`assertion ${item.status}`} key={index}><strong>{item.status === "passed" ? "Passed" : "Failed"}</strong> {item.message}{item.status === "failed" && <small>expected: {objectText(item.expected)} actual: {objectText(item.actual)}</small>}</div>)}{latest?.nodeResults?.[0]?.failureKind && <p className="api-error">Failure: {latest.nodeResults[0].failureKind}</p>}</section>}
    {observed && replayNode && <section className="response-diff"><h3>Observed → Replay</h3><table><thead><tr><th>Field</th><th>Observed</th><th>Replay</th></tr></thead><tbody>{diffRows.map(([field, left, right]) => <tr key={field} className={Object.is(left, right) ? "unchanged" : "changed"}><th>{field}</th><td>{objectText(left ?? "not stored")}</td><td>{objectText(right ?? "not stored")}</td></tr>)}</tbody></table></section>}
    <details className="schema-details"><summary><span><strong>Request/response schema</strong><small>OpenAPI에 정의된 요청과 응답 구조</small></span><i aria-hidden="true"/></summary><div className="schema-sections"><section><h4><span>Request</span><small>{operation.requestBody?.media?.[0]?.contentType ?? "No content type"}</small></h4><pre>{objectText(operation.requestBody ?? "No request schema")}</pre></section><section><h4><span>Responses</span><small>{operation.responseBranches.length} branches</small></h4><pre>{objectText(operation.responseBranches)}</pre></section></div></details>
  </aside>;
}
