import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createServer, type RequestListener, type Server } from "node:http";
import { evaluateApiAssertions } from "./assertions";
import { normalizeExecution, mergeNodeResults } from "./execution";
import { redactHeaders, redactUrl, redactValue } from "./security";
import { loadOpenApiSources } from "../openapi/loader";
import { apiNodeState, openApiOperationId, operationTestState, parseOpenApiDocument } from "../openapi/catalog";
import { ApiExecutionAdapter } from "../vite/api-execution-adapter";
import { classifyApiTest, matchObservedApiCase, matchResponseBranch, responseBranchCoverage, validateResponseEdges } from "./api-response";
import { validateOpenApiSchema } from "../vite/openapi-schema-validator";
import { matchNetworkOperation } from "../openapi/network-match";
import { normalizeApiCases } from "./api-cases";
import { scenarioActs, scenarioNodeContext } from "./scenario-acts";
import type { OpenApiOperation, ScenarioGraph } from "./types";

const document = { openapi: "3.0.3", info: { title: "Test", version: "1" }, paths: { "/jobs/{id}": { post: { operationId: "retryJob", tags: ["Jobs"], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" }, example: "abc" }, { name: "verbose", in: "query", schema: { type: "boolean" } }, { name: "X-Tenant", in: "header", schema: { type: "string" } }], requestBody: { content: { "application/json": { schema: { type: "object" }, example: { force: false } } } }, responses: { "200": { description: "Queued", content: { "application/json": { schema: { type: "object" }, example: { status: "queued" } } } } } } } } };
const graph: ScenarioGraph = { id: "retry", title: "Retry", source: "e2e/retry.spec.ts", execution: { grep: "retry" }, nodes: [{ id: "api", title: "Retry API", kind: "api", ref: openApiOperationId("test", "POST", "/jobs/{id}") }], edges: [] };

describe("platform model", () => {
  it("normalizes legacy and explicit executions", () => { expect(normalizeExecution(graph)).toEqual({ adapter: "playwright", source: graph.source, grep: "retry" }); expect(normalizeExecution({ execution: { adapter: "api", request: { operationId: "retryJob" } } })).toMatchObject({ adapter: "api" }); });
  it("merges node results and generalized artifacts", () => { const merged = mergeNodeResults(graph, [{ runId: "run-1", origin: "api-replay", nodeId: "api", status: "passed", durationMs: 12, artifacts: [{ type: "response", label: "200", url: "", httpStatus: 200, runId: "run-1" }] }]); expect(merged.nodes[0]).toMatchObject({ status: "passed", metadata: { durationMs: 12 }, artifacts: [{ type: "response" }], latestResult: { runId: "run-1" } }); });
  it("deduplicates a run and separates latest result from history", () => { const first = { runId: "run-1", origin: "api-replay" as const, nodeId: "api", status: "passed" as const, artifacts: [{ type: "response" as const, label: "200", url: "", runId: "run-1" }] }; const repeated = mergeNodeResults(mergeNodeResults(graph, [first]), [first]); expect(repeated.nodes[0].artifacts).toHaveLength(1); expect(repeated.nodes[0].resultHistory).toHaveLength(1); const second = mergeNodeResults(repeated, [{ ...first, runId: "run-2", status: "failed" }]); expect(second.nodes[0].latestResult?.runId).toBe("run-2"); expect(second.nodes[0].resultHistory?.map((item) => item.runId)).toEqual(["run-1", "run-2"]); });
  it("evaluates API assertions individually", () => { const results = evaluateApiAssertions([{ type: "status", equals: 200 }, { type: "json-path", path: "$.status", equals: "queued" }, { type: "exists", path: "missing" }, { type: "duration", lessThanMs: 500 }, { type: "content-type", includes: "json" }], { status: 200, durationMs: 10, headers: { "content-type": "application/json" }, body: { status: "queued" } }); expect(results.map((item) => item.status)).toEqual(["passed", "passed", "failed", "passed", "passed"]); });
  it("redacts sensitive headers and URL query values", () => { expect(redactHeaders({ Authorization: "Bearer secret", Cookie: "sid=secret", Accept: "json" })).toEqual({ Authorization: "[REDACTED]", Cookie: "[REDACTED]", Accept: "json" }); expect(redactUrl("https://example.test/items?access_token=secret&q=safe")).not.toContain("access_token=secret"); });
  it("redacts configured keys across snake and camel case", () => { expect(redactValue({ access_token: "one", accessToken: "two", nested: { credential: "three" } }, ["accessToken", "credential"])).toEqual({ access_token: "[REDACTED]", accessToken: "[REDACTED]", nested: { credential: "[REDACTED]" } }); });
  it("calculates linked and tested operation state", () => { const id = graph.nodes[0].ref!; expect(operationTestState({ name: "suite", scenarios: [graph] }, id)).toBe("untested"); expect(operationTestState({ name: "suite", scenarios: [{ ...graph, nodes: [{ ...graph.nodes[0], status: "passed" }] }] }, id)).toBe("passed"); expect(operationTestState({ name: "suite", scenarios: [graph] }, `${id}:missing`)).toBe("unlinked"); });
  it("distinguishes documented and undocumented API nodes", () => { const catalog = parseOpenApiDocument({ id: "test", title: "Test" }, document); expect(apiNodeState(graph.nodes[0], catalog)).toBe("documented"); expect(apiNodeState({ ...graph.nodes[0], ref: "openapi:missing:GET:/" }, catalog)).toBe("undocumented"); });
  it("normalizes legacy API node input to a request-only default case", () => { expect(normalizeApiCases({ ...graph.nodes[0], request: { path: { id: "one" } }, assertions: [{ type: "status", equals: 200 }] })[0]).toMatchObject({ id: "default", request: { path: { id: "one" } }, setup: { type: "request-only" } }); });
  it("groups consecutive scenario steps into acts and exposes their flow", () => { const scenario: ScenarioGraph = { id: "flow", title: "Flow", nodes: [{ id: "setup", title: "Setup", kind: "fixture" }, { id: "screen", title: "Screen", kind: "screen", layer: "ui" }, { id: "click", title: "Click", kind: "action", layer: "ui" }, { id: "request", title: "Request", kind: "api", layer: "api" }, { id: "done", title: "Done", kind: "outcome" }], edges: [{ id: "one", source: "setup", target: "screen" }, { id: "two", source: "screen", target: "click" }, { id: "three", source: "click", target: "request" }, { id: "four", source: "request", target: "done", response: "200" }] }; expect(scenarioActs(scenario).map((act) => [act.title, act.nodes.length])).toEqual([["Setup", 1], ["UI", 2], ["API", 1], ["Verification", 1]]); expect(scenarioNodeContext(scenario, "request")).toMatchObject({ actIndex: 2, stepIndex: 0, incoming: [{ node: { id: "click" } }], outgoing: [{ edge: { response: "200" }, node: { id: "done" } }] }); });
});

describe("OpenAPI import", () => {
  const dirs: string[] = []; afterEach(async () => Promise.all(dirs.splice(0).map((dir) => rm(dir, { recursive: true }))));
  it("extracts parameters, request and response examples", () => { const operation = parseOpenApiDocument({ id: "test", title: "Test API" }, document).operations[0]; expect(operation.id).toBe("openapi:test:POST:/jobs/{id}"); expect(operation.parameters.map((item) => item.in)).toEqual(["path", "query", "header"]); expect(operation.requestBody?.media[0].example).toEqual({ force: false }); expect(operation.responses[0].media?.[0].example).toEqual({ status: "queued" }); });
  it("loads JSON and YAML and reports invalid documents", async () => { const dir = await mkdtemp(path.join(tmpdir(), "baekstage-openapi-")); dirs.push(dir); await writeFile(path.join(dir, "api.json"), JSON.stringify(document)); await writeFile(path.join(dir, "api.yaml"), "openapi: 3.0.3\ninfo: {title: Test, version: '1'}\npaths:\n  /health:\n    get:\n      responses:\n        '200': {description: OK}\n"); await writeFile(path.join(dir, "bad.yaml"), "openapi: 2.0\npaths: {}\n"); const catalog = await loadOpenApiSources(dir, [{ id: "json", title: "JSON", file: "api.json" }, { id: "yaml", title: "YAML", file: "api.yaml" }, { id: "bad", title: "Bad", file: "bad.yaml" }]); expect(catalog.operations).toHaveLength(2); expect(catalog.errors?.[0].message).toContain("OpenAPI 3.x"); });
});

describe("response branches", () => {
  const branches = parseOpenApiDocument({ id: "branch", title: "Branch", baseUrl: "https://api.test" }, { openapi: "3.0.3", components: { schemas: { Error: { allOf: [{ type: "object", required: ["code"], properties: { code: { oneOf: [{ type: "string" }, { type: "integer" }] }, detail: { type: "string", nullable: true } } }] } } }, paths: { "/jobs/{id}": { get: { responses: { "200": { description: "OK" }, "4XX": { description: "Client error", headers: { "X-Error": { schema: { type: "string" } } }, content: { "application/json": { schema: { $ref: "#/components/schemas/Error" }, example: { code: "BAD" } } } }, default: { description: "Fallback" } } } } } }).operations[0];
  it("prefers exact, then range, then default and reports undocumented", () => { expect(matchResponseBranch(branches, 200).matchType).toBe("exact"); expect(matchResponseBranch(branches, 409).matchType).toBe("range"); expect(matchResponseBranch(branches, 503).matchType).toBe("default"); const withoutDefault = { ...branches, responseBranches: branches.responseBranches.filter((item) => item.statusPattern !== "default") }; expect(matchResponseBranch(withoutDefault, 503).matchType).toBe("undocumented"); });
  it("passes expected errors and fails unexpected errors", () => { const response = { status: 409, statusText: "Conflict", durationMs: 1, headers: {}, documented: true, branchId: `${branches.id}:response:4XX`, matchType: "range" as const }; expect(classifyApiTest(response, { id: "conflict", title: "Conflict", expectedResponse: "4XX" }, [])).toEqual({ passed: true }); expect(classifyApiTest(response, { id: "ok", title: "OK", expectedResponse: "200" }, [])).toMatchObject({ passed: false, failureKind: "unexpected-status" }); expect(classifyApiTest({ ...response, status: 500 }, undefined, [])).toMatchObject({ passed: false, failureKind: "unexpected-status" }); });
  it("extracts content, example, headers and validates local refs/composition", () => { const branch = branches.responseBranches.find((item) => item.statusPattern === "4XX")!; expect(branch).toMatchObject({ contentTypes: ["application/json"], example: { code: "BAD" }, headers: [{ name: "X-Error" }] }); expect(validateOpenApiSchema(branch.schema, branches.schemaComponents, { code: "BAD", detail: null }).valid).toBe(true); expect(validateOpenApiSchema(branch.schema, branches.schemaComponents, {}).valid).toBe(false); });
  it("calculates coverage and validates response edges", () => { const scenario = { ...graph, nodes: [{ ...graph.nodes[0], ref: branches.id, cases: [{ id: "client", title: "client", expectedResponse: "4XX" }] }], edges: [{ id: "client", source: "api", target: "api", branch: true, response: "4XX" }] }; expect(responseBranchCoverage(branches, scenario, "api").find((item) => item.branch.statusPattern === "4XX")).toMatchObject({ connected: true, hasCase: true, tested: false }); expect(validateResponseEdges(scenario, [branches])).toEqual([]); expect(validateResponseEdges({ ...scenario, edges: [{ ...scenario.edges[0], response: "409" }] }, [branches])[0]).toContain("does not document"); });
  it("matches observed paths without choosing ambiguous operations", () => { expect(matchNetworkOperation([branches], "GET", "https://api.test/jobs/abc")).toMatchObject({ status: "matched", operation: { id: branches.id } }); expect(matchNetworkOperation([branches, { ...branches, id: "duplicate" }], "GET", "https://api.test/jobs/abc").status).toBe("ambiguous"); });
  it("normalizes encoded paths, trailing slashes, base paths and query order", () => { const based = { ...branches, path: "/jobs/{id}", baseUrl: "https://api.test/v1" }; for (const url of ["https://api.test/v1/jobs/a%20b/", "https://api.test/v1/jobs/a%20b?z=2&a=1", "https://api.test/v1/jobs/a%20b?a=1&z=2"]) expect(matchNetworkOperation([based], "GET", url).status).toBe("matched"); expect(matchNetworkOperation([based], "POST", "https://api.test/v1/jobs/a").status).toBe("undocumented"); });
  it("honors explicit operation/source hints and ignored observations", () => { const duplicate = { ...branches, id: "openapi:other:GET:/jobs/{id}", sourceId: "other" }; expect(matchNetworkOperation([branches, duplicate], "GET", "https://api.test/jobs/abc", { sourceId: "branch" }).operation?.id).toBe(branches.id); expect(matchNetworkOperation([branches], "GET", "https://api.test/jobs/abc", { ignored: true }).status).toBe("ignored"); expect(matchNetworkOperation([branches], "GET", "https://other.test/jobs/abc").status).toBe("undocumented"); });
  it("matches observed cases only when branch/request or hint is unambiguous", () => { const request = { timestamp: "now", method: "GET", url: "https://api.test/jobs/running", headers: {}, bodyStored: false, bodyStorageReason: "disabled" as const }; const cases = [{ id: "running", title: "Running", expectedResponse: "4XX", request: { path: { id: "running" } } }, { id: "missing", title: "Missing", expectedResponse: "4XX", request: { path: { id: "missing" } } }]; expect(matchObservedApiCase(cases, branches, request, 409, "range")).toMatchObject({ status: "matched", testCase: { id: "running" } }); expect(matchObservedApiCase(cases.map((item) => ({ ...item, request: undefined })), branches, request, 409, "range").status).toBe("ambiguous"); expect(matchObservedApiCase([], branches, request, 409, "range").status).toBe("observed-only"); expect(matchObservedApiCase(cases, branches, request, 409, "range", "missing")).toMatchObject({ status: "matched", testCase: { id: "missing" } }); });
});

describe("API execution adapter", () => {
  let server: Server | undefined; afterEach(() => server?.close());
  async function fixture(handler: RequestListener) { server = createServer(handler); await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve)); const address = server.address(); return `http://127.0.0.1:${typeof address === "object" && address ? address.port : 0}`; }
  function operation(baseUrl: string): OpenApiOperation { return { ...parseOpenApiDocument({ id: "test", title: "Test", baseUrl }, document).operations[0] }; }
  it("runs an allowed operation, keeps non-2xx responses, and redacts secrets", async () => { const base = await fixture((req, res) => { res.writeHead(401, { "content-type": "application/json", "set-cookie": "secret=yes" }); res.end(JSON.stringify({ status: "denied" })); }); const op = operation(base); const result = await new ApiExecutionAdapter([{ id: "test", baseUrl: base }], [op]).run({ sourceId: "test", operationId: op.id, path: { id: "abc" }, headers: { Authorization: "Bearer secret", "Content-Type": "application/json" }, assertions: [{ type: "status", equals: 200 }] }, { scenarioId: "retry", nodeId: "api" }); const response = result.nodeResults?.[0].api?.response; expect(response?.status).toBe(401); expect(response?.headers["set-cookie"]).toBe("[REDACTED]"); expect(JSON.stringify(result)).not.toContain("Bearer secret"); expect(result.nodeResults?.[0].status).toBe("failed"); });
  it("rejects unknown sources and arbitrary operations", async () => { const adapter = new ApiExecutionAdapter([], []); await expect(adapter.run({ sourceId: "evil", operationId: "https://example.com", path: {} }, { scenarioId: "x" })).rejects.toMatchObject({ status: 403 }); });
  it("treats an expected 409 as passed and an unexpected 500 as failed", async () => { const base = await fixture((req, res) => { const status = req.url?.includes("conflict") ? 409 : 500; res.writeHead(status, { "content-type": "application/json" }); res.end(JSON.stringify({ code: status === 409 ? "CONFLICT" : "FAIL" })); }); const op = parseOpenApiDocument({ id: "cases", title: "Cases", baseUrl: base }, { openapi: "3.0.3", paths: { "/jobs/{id}": { post: { responses: { "200": { description: "OK" }, "409": { description: "Conflict", content: { "application/json": { schema: { type: "object", required: ["code"] } } } }, "500": { description: "Failure", content: { "application/json": { schema: { type: "object" } } } } } } } } }).operations[0]; const adapter = new ApiExecutionAdapter([{ id: "cases", baseUrl: base }], [op]); const expected = await adapter.run({ sourceId: "cases", operationId: op.id, path: { id: "conflict" }, caseId: "conflict", expectedResponse: "409", assertions: [{ type: "status", equals: 409 }] }, { scenarioId: "x", nodeId: "api" }); expect(expected.nodeResults?.[0]).toMatchObject({ status: "passed", caseId: "conflict", api: { response: { status: 409, matchType: "exact" } } }); const unexpected = await adapter.run({ sourceId: "cases", operationId: op.id, path: { id: "failure" } }, { scenarioId: "x", nodeId: "api" }); expect(unexpected.nodeResults?.[0]).toMatchObject({ status: "failed", failureKind: "unexpected-status" }); });
  it("enforces timeout and response size", async () => { const base = await fixture((_req, res) => { setTimeout(() => res.end("late"), 50); }); const op = operation(base); const timedOut = await new ApiExecutionAdapter([{ id: "test", baseUrl: base }], [op], { timeoutMs: 5 }).run({ sourceId: "test", operationId: op.id, path: { id: "abc" } }, { scenarioId: "x", nodeId: "api" }); expect(timedOut.nodeResults?.[0].failureKind).toBe("timeout"); server?.close(); const largeBase = await fixture((_req, res) => { res.end("123456789"); }); const largeOp = operation(largeBase); const tooLarge = await new ApiExecutionAdapter([{ id: "test", baseUrl: largeBase }], [largeOp], { maxResponseBytes: 4 }).run({ sourceId: "test", operationId: largeOp.id, path: { id: "abc" } }, { scenarioId: "x", nodeId: "api" }); expect(tooLarge.nodeResults?.[0].failureKind).toBe("response-too-large"); });
});
